export const cursorAiGuide = {
  slug: "cursor-ai",
  title: "Cursor AI",
  subtitle: "The AI Code Editor That Writes With You",
  version: "0.45",
  lastUpdated: "February 19, 2026",
  readTime: "30 min",
  totalPages: 40,
  previewPages: 10,
  price: "$29",
  priceId: "price_1T2ZHHH2EmpwQ8mJyumtvN5c",
  buyUrl: "https://ohamm.gumroad.com",
  badge: "Trending Now",
  whoItsFor: [
    "You write code daily (any language)",
    "You waste time Googling syntax",
    "You copy-paste from Stack Overflow more than you'd like to admit",
    "You work on unfamiliar codebases often",
    "You want AI help without leaving your editor",
  ],
  skipIf: [
    "You write less than 5 hours of code per week",
    "You're happy with GitHub Copilot + ChatGPT (separate tools)",
    "You need on-premise deployment (Cursor is cloud-connected)",
  ],
  sections: [
    {
      page: 1,
      number: "01",
      action: "It's VS Code, But Smarter",
      body: "Cursor is a code editor built on top of VS Code. It looks identical. Your extensions work. Your settings import. The difference? AI lives inside it.\n\nPress Cmd+K and type what you want. Cursor writes the code. Press Cmd+L and ask it to explain something. It reads your entire codebase to answer.\n\nThis isn't autocomplete on steroids. This is AI that understands context.",
      whisper: "Your setup will look exactly like VS Code — just with AI built in.",
      screenshotAlt: "Cursor interface with AI chat panel open on right side, showing code on left and conversation on right",
    },
    {
      page: 2,
      number: "03",
      action: "Download and Install",
      body: "Step 1: Visit cursor.sh and click \"Download for Mac\" (or Windows/Linux).\n\nStep 2: Open the .dmg and drag to Applications. Windows users: run the .exe installer.\n\nStep 3: Open Cursor for the first time. It will ask to import VS Code settings. Click \"Yes\" if you use VS Code. Click \"Skip\" if you're starting fresh.",
      whisper: "Import your settings or start fresh — both work fine.",
      screenshotAlt: "Cursor first-run dialog showing Import VS Code Settings with Yes/Skip buttons",
    },
    {
      page: 2,
      number: "04",
      action: "Sign In (Required for AI Features)",
      body: "Cursor needs an account to use AI features. Free tier includes 2,000 completions per month.\n\nClick \"Sign In\" in the top-right. Choose Google (easiest), GitHub (recommended for devs), or email. Verify your email. You're in.",
      whisper: "Free tier is generous enough for part-time use. Pro ($20/mo) is unlimited.",
      screenshotAlt: "Cursor sign-in screen with Google, GitHub, and Email buttons",
    },
    {
      page: 3,
      number: "05",
      action: "Cmd+K: AI Code Generation",
      body: "Generates or edits code based on your instructions.\n\n1. Highlight code you want to change (or place cursor where you want new code)\n2. Press Cmd+K (Windows: Ctrl+K)\n3. Type your instruction in plain English\n4. Press Enter\n5. Cursor generates code inline\n\nExample: \"Add error handling for network timeouts\" — Cursor inserts try-catch blocks, timeout logic, and proper error messages. Review. Accept or reject.",
      whisper: "Generated code appears inline with your existing code. Accept to keep it, reject to discard.",
      screenshotAlt: "Cmd+K prompt showing inline code generation with Accept/Reject buttons",
    },
    {
      page: 3,
      number: "06",
      action: "Cmd+L: AI Chat (Codebase-Aware)",
      body: "Answers questions about your code. Reads your entire project for context.\n\nPress Cmd+L — chat panel opens on the right. Ask anything:\n\n\"Where is user authentication handled?\"\n\"What database library are we using?\"\n\"How do I add a new API endpoint?\"\n\nCursor searches files and responds with references. Click file names to jump directly there.",
      whisper: "Chat references actual files in your project. Click file names to jump to them.",
      screenshotAlt: "Cmd+L chat panel showing a question and answer with file references",
    },
    {
      page: 4,
      number: "07",
      action: "Write New Code from Scratch",
      body: "Scenario: You need a function but don't remember the syntax.\n\nType a comment describing what you need, highlight it, press Cmd+K, type \"write this function.\" Cursor generates a complete function with error handling, type annotations, and documentation.\n\nAccept if it looks right. Reject and refine if not.",
      whisper: "Comments are the best prompts. Write what you want in plain English, then let Cursor implement it.",
      screenshotAlt: "Code editor showing a comment prompt and AI-generated function below it",
    },
    {
      page: 4,
      number: "08",
      action: "Refactor Existing Code",
      body: "Scenario: You have messy code that works but needs cleanup.\n\nHighlight the messy code, press Cmd+K, type \"refactor this to be more readable.\" Cursor rewrites it with better variable names, modern syntax, and cleaner structure. Same functionality, half the lines.",
      whisper: "Cursor knows modern best practices for your language. It'll use array methods, destructuring, and clean patterns automatically.",
      screenshotAlt: "Before and after code side by side showing refactoring improvement",
    },
    {
      page: 7,
      number: "13",
      action: "Be Specific, Not Vague",
      body: "Bad prompt: \"make this better\" — Good prompt: \"add input validation for email and phone number\"\n\nBad prompt: \"fix the bug\" — Good prompt: \"fix the null pointer exception on line 42\"\n\nCursor isn't a mind reader. Specificity = better results. Include the language, the library, and the desired outcome.",
      whisper: "The more context you give, the better the output. Treat Cursor like a smart but new teammate.",
    },
    {
      page: 8,
      number: "15",
      action: "Reject and Refine",
      body: "If generated code is wrong: Click \"Reject\" (or press Esc). Press Cmd+K again. Be more specific: \"use async/await instead of promises\" or \"use the Stripe Node SDK v20.\"\n\nCommon fixes: specify the library version, tell it what edge cases to handle, describe your project's code style.",
      whisper: "Most code improves dramatically with one refinement. Don't accept the first try if it's not right.",
    },
    {
      page: 8,
      number: "16",
      action: "Check Generated Code Before Running",
      body: "Always review AI-generated code. Quick checks:\n\n• Does it use libraries you actually have installed?\n• Are variable names consistent with your codebase?\n• Does it handle errors gracefully?\n• Are there obvious security issues? (SQL injection, XSS, etc.)\n\nTreat AI code like code from a smart but sometimes careless colleague — review before merging.",
      whisper: "The 30-second review saves the 3-hour debugging session.",
    },
  ],
  tableOfContents: [
    { section: "Quick Start", pages: "1-10", items: "Installation, Cmd+K, Cmd+L, code generation, refactoring, prompt tips" },
    { section: "Advanced Techniques", pages: "11-20", items: "Layered prompts, multi-file refactoring, .cursorrules, debugging with AI, team code review" },
    { section: "Team & Enterprise", pages: "21-30", items: "Team licenses, onboarding, style consistency, AI code in CI/CD, security practices" },
    { section: "Power User & Real-World", pages: "31-40", items: "TypeScript, React, Go, Rust tips, SQL generation, API scaffolding, test generation, case studies" },
  ],
  fullGuideIncludes: [
    "40 pages of actionable techniques — zero filler",
    "Advanced prompting: layered prompts, comment-as-spec, multi-file context",
    "Multi-file refactoring workflows across entire codebases",
    ".cursorrules and .cursorignore configuration",
    "Debugging with AI: find bugs, trace issues, fix faster",
    "Team workflows: shared rules, code review, onboarding",
    "CI/CD integration: pre-commit hooks, automated workflows",
    "Privacy and security: what data Cursor sends, how to block sensitive files",
    "Language-specific tips: TypeScript, React, Go, Rust, SQL, CSS",
    "Real-world case studies: legacy refactoring, API generation, test scaffolding",
  ],
};
