export const openclawMacSetupGuide = {
  slug: "openclaw-mac-setup",
  title: "OpenClaw",
  subtitle: "Your Personal AI Agent, Running on Your Mac",
  version: "2026.2",
  lastUpdated: "February 2026",
  readTime: "25 min",
  totalPages: 35,
  previewPages: 8,
  price: "$29",
  priceId: "price_openclaw_mac_setup", // TODO: Create Stripe price
  buyUrl: "https://ohamm.gumroad.com",
  badge: "New",
  whoItsFor: [
    "You want an AI assistant that runs locally on your Mac",
    "You're tired of copy-pasting between ChatGPT and your terminal",
    "You want AI that can read your files, run commands, and browse the web",
    "You manage multiple projects and want AI automation",
    "You've heard of AI agents but don't know where to start",
  ],
  skipIf: [
    "You're on Windows or Linux (Mac-only for now)",
    "You only need occasional ChatGPT questions",
    "You're not comfortable with a terminal at all",
  ],
  sections: [
    {
      page: 1,
      number: "01",
      action: "What OpenClaw Actually Is",
      body: "OpenClaw is an AI agent that runs on your Mac. Not a chatbot. Not an API wrapper. An agent.\n\nIt reads your files. It runs shell commands. It browses the web. It sends messages. It remembers context between sessions. It can even control your browser.\n\nThink of it as an AI coworker that lives on your machine and never sleeps.",
      whisper: "This is the tool that changes how you think about AI — from asking questions to delegating work.",
      screenshotAlt: "OpenClaw dashboard showing connected agents, active sessions, and system status",
    },
    {
      page: 2,
      number: "02",
      action: "Prerequisites: What You Need",
      body: "Before installing OpenClaw, make sure you have:\n\n1. A Mac running macOS 13+ (Ventura or later)\n2. Node.js 20+ installed (check with 'node --version')\n3. An Anthropic API key (for Claude) or OpenAI API key\n4. Basic comfort with Terminal\n\nIf you don't have Node.js, install it with Homebrew: 'brew install node'. If you don't have Homebrew, visit brew.sh first.",
      whisper: "Most Mac developers already have these. If not, each takes under 5 minutes to set up.",
      screenshotAlt: "Terminal showing node --version output confirming Node.js 20+",
    },
    {
      page: 3,
      number: "03",
      action: "Install OpenClaw in One Command",
      body: "Open Terminal and run: npm install -g openclaw\n\nThat's it. OpenClaw is now installed globally. Verify with: openclaw --version\n\nThe installer sets up the CLI, the local gateway server, and your workspace directory at ~/.openclaw/workspace.",
      whisper: "One command. No Docker. No VMs. No cloud setup. It runs right on your Mac.",
      screenshotAlt: "Terminal showing npm install -g openclaw completing successfully",
    },
    {
      page: 4,
      number: "04",
      action: "First Run: Start the Gateway",
      body: "Run: openclaw gateway start\n\nThis starts the local server that manages your AI sessions. It runs in the background as a LaunchAgent — meaning it survives reboots.\n\nCheck status with: openclaw status\n\nYou should see the gateway running, your workspace path, and available tools listed.",
      whisper: "The gateway is lightweight. It uses minimal resources when idle.",
      screenshotAlt: "Terminal showing openclaw status with gateway running, workspace path, and tools listed",
    },
    {
      page: 5,
      number: "05",
      action: "Connect Your AI Provider",
      body: "OpenClaw needs an AI model to think with. The recommended setup is Anthropic's Claude.\n\nRun: openclaw config set anthropic.apiKey YOUR_KEY_HERE\n\nOr for OpenAI: openclaw config set openai.apiKey YOUR_KEY_HERE\n\nYou can use multiple providers. OpenClaw lets you switch models per session.",
      whisper: "Claude Opus is the most capable, but Sonnet is faster and cheaper for routine tasks.",
      screenshotAlt: "Terminal showing API key configuration with masked key value",
    },
    {
      page: 6,
      number: "06",
      action: "Your First Conversation",
      body: "Connect a messaging channel. The fastest way: Telegram.\n\n1. Create a bot via @BotFather on Telegram\n2. Copy the bot token\n3. Run: openclaw config set telegram.botToken YOUR_TOKEN\n4. Message your bot on Telegram\n\nYour AI agent is now live. It can read files, run commands, search the web, and remember everything you tell it.",
      whisper: "Telegram is the easiest channel. Discord, Signal, and others work too.",
      screenshotAlt: "Telegram chat showing a conversation with an OpenClaw-powered bot",
    },
    {
      page: 7,
      number: "07",
      action: "The Workspace: Your Agent's Home",
      body: "Everything your agent needs lives in ~/.openclaw/workspace.\n\nSOUL.md defines your agent's personality. MEMORY.md is its long-term memory. TOOLS.md lists available tools and credentials. The memory/ folder stores daily logs.\n\nEdit these files to customize your agent. It reads them at the start of every session.",
      whisper: "Think of the workspace as your agent's brain. The better you set it up, the smarter it gets.",
      screenshotAlt: "File explorer showing workspace structure with SOUL.md, MEMORY.md, TOOLS.md, and memory folder",
    },
    {
      page: 8,
      number: "08",
      action: "Heartbeats: Proactive AI",
      body: "OpenClaw doesn't just wait for you to ask. With heartbeats, your agent checks in periodically.\n\nCreate HEARTBEAT.md in your workspace with a checklist of things to monitor — email, calendar, project status, whatever matters to you.\n\nYour agent will run through the checklist on a schedule and only ping you when something needs attention.",
      whisper: "This is where OpenClaw goes from chatbot to agent. Set it and forget it.",
      screenshotAlt: "HEARTBEAT.md file showing a checklist with email, calendar, and project monitoring items",
    },
  ],
  tableOfContents: [
    { section: "Getting Started", pages: "1-8", items: "What OpenClaw is, prerequisites, installation, first run, provider setup, first conversation, workspace, heartbeats" },
    { section: "Power Features", pages: "9-16", items: "Browser automation, file operations, shell commands, web search, memory system, cron jobs, sub-agents" },
    { section: "Channel Setup", pages: "17-22", items: "Telegram, Discord, Signal, Slack, WhatsApp — full setup for each" },
    { section: "Customization", pages: "23-28", items: "SOUL.md personality, skills, tool policies, security hardening, multi-agent setups" },
    { section: "Real Workflows", pages: "29-35", items: "Daily assistant, code reviewer, research agent, content creator, DevOps monitor — complete recipes" },
  ],
  fullGuideIncludes: [
    "35-page complete setup guide",
    "5 channel setup walkthroughs",
    "8 real workflow recipes",
    "Security hardening checklist",
    "Multi-agent architecture patterns",
    "Troubleshooting guide",
    "Free lifetime updates",
    "30-day money-back guarantee",
  ],
};
